BEGIN;

INSERT INTO blogful_articles (title, content, date_published) 
VALUES
('For Ebola in the Democratic Republic of the Congo, the end will have to wait', 
'Not doing something will always be faster than doing it.', 
'10 April 2020'),
('Is this telescope-on-a-plane worth its pricetag?',
'NASA’s high-flying SOFIA observatory has struggled to prove its scientific worth.',
'08 April 2020'),
('People power: How India is attempting to slow the coronavirus',
'Without enough test kits, the 1.3-billion-person country is using a gigantic surveillance network to trace and…',
'09 April 2020'),
('Coronapod: An untapped resource',
'The labs struggling to get involved in diagnostic testing, and should you be wearing a mask?',
'11 April 2020'),
('Coronavirus diaries: hello from home',
'John Tregoning gets to grips with a new world of work.',
'13 April 2020'),
('Coronavirus latest: UK launches massive diagnostic network',
'Updates on the respiratory illness that has infected more than one million people and killed tens of thousands.',
'09 April 2020'),
('Why daily death tolls have become unusually important in understanding the coronavirus pandemic',
'COVID-19’s lethality provides a grim opportunity to track its spread.',
'14 April 2020'),
('Six ways to juggle science and childcare from home',
'In the face of COVID-19 restrictions on daily life, scientist-parents describe their efforts to balance family and work duties.',
'15 April 2020'),
('Mission control on Skype: how to fly a spacecraft during a pandemic',
'BepiColombo is about to fly past Earth on its way to Mercury — but coronavirus precautions mean that most of its…',
'11 March 2020'),
('Nature to join open-access Plan S, publisher says',
'Springer Nature says it commits to offering researchers a route to publishing open access in Nature and most…',
'13 March 2020'),
('Daily briefing: This is the state of COVID-19 vaccine development now',
'There are 78 confirmed COVID-19 vaccine candidates, 5 of which have already entered clinical trials. Plus: an… ',
'16 March 2020'),
('The gluconeogenic enzyme PCK1 phosphorylates INSIG1/2 for lipogenesis',
'Phosphorylation of INSIG1 and INSIG2 by PCK1 leads to a reduction in the binding of sterols, the activation of…',
'17 February 2020'),
('The projected timing of abrupt ecological disruption from climate change',
'Using annual projections of temperature and precipitation to estimate when species will be exposed to potentially…',
'13 May 2020'),
('A reference map of the human binary protein interactome',
'A human binary protein interactome map that includes around 53,000 protein–protein interactions involving more…',
'15 April 2020'),
('Coronavirus in cats, climate cancellation and missing African trials',
'The latest science news, in brief.',
'22 March 2020'),
('A neural circuit mechanism for mechanosensory feedback control of ingestion',
'A population of neurons in the parabrachial nucleus that expresses prodynorphin monitors ingestion using…',
'05 January 2020'),
('AIM2 inflammasome surveillance of DNA damage shapes neurodevelopment',
'The sensing of DNA damage by the AIM2 inflammasome promotes the death of central nervous system cells and is…',
'02 May 2020'),
('Podcast: A plastic-recycling enzyme, and supercooled molecules',
'Hear about the latest science, with Nick Howe and Shamini Bundell.',
'03 June 2020'),
('A general carbonyl alkylative amination for tertiary amine synthesis',
'Roopender Kumar, Nils J.',
'07 June 2020'),
('Early Holocene crop cultivation and landscape modification in Amazonia',
'Archaeological evidence that anthropic landscape changes and crop cultivation in southwestern Amazonia began…',
'08 August 2020')
;

COMMIT;